[versions]
androidGradlePlugin = "8.7.3"
androidxCarApp = "1.7.0-rc01"

[libraries]
android-tools = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
google-services = { module = "com.google.gms:google-services", version = "4.4.2" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version = "3.0.2" }
google-firebase-appdistribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version = "5.0.0" }
triplet-play-publisher = { module = "com.github.triplet.gradle:play-publisher", version = "3.10.1" }
huawei-publish = { module = "ru.cian:huawei-publish-gradle-plugin", version = "1.4.2" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.4" }
google-services-location = { module = "com.google.android.gms:play-services-location", version = "21.3.0" }
microg-services-location = { module = "org.microg.gms:play-services-location", version = "0.3.6.244735" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version = "33.5.1" }
androidx-core = { module = "androidx.core:core", version = "1.15.0" }
jetbrains-kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version = "2.1.10" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.9.1" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-car-app = { module = "androidx.car.app:app", version.ref = "androidxCarApp" }
androidx-car-app-projected = { module = "androidx.car.app:app-projected", version.ref = "androidxCarApp" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }
androidx-fragment = { module = "androidx.fragment:fragment", version = "1.8.5" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.1" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version = "2.10.0" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version = "2.8.7" }
android-material = { module = "com.google.android.material:material", version = "1.12.0" }
google-guava = { module = "com.google.guava:guava", version = "33.3.0-android" }
devnullorthrow-mpandroidchart = { module = "com.github.devnullorthrow:MPAndroidChart", version = "3.2.0-alpha" }
jcip-annotations = { module = "net.jcip:jcip-annotations", version = "1.0" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
junit = { module = "junit:junit", version = "4.13.2" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.15.2" }
mockito-inline = { module = "org.mockito:mockito-inline", version = "5.2.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library= { id = "com.android.library", version.ref = "androidGradlePlugin" }
