name: Check
on:
  push:
  pull_request:

jobs:
  android-check:
    name: Android Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure
        shell: bash
        run: |
          ./configure.sh

      - name: Set up SDK
        shell: bash
        run: |
          (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT --ndk $ANDROID_NDK_ROOT)

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: android/nativeOutputs
          key: android-cache

      - name: Compile
        shell: bash
        run: (cd android; ./gradlew -Parm64 assembleWebDebug)

      - name: Upload arm64-v8a debug apk
        uses: actions/upload-artifact@v2
        with:
          name: android-web-arm64-v8a-debug
          path: android/build/outputs/apk/android-web-debug-*.apk
          if-no-files-found: error
