name: Android Check
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths-ignore:
      - .gitignore
      - .github/**
      - '!.github/workflows/android-check.yaml'  # Run check on self change
      - '**/*_tests/**'
      - CONTRIBUTORS
      - LICENSE
      - NOTICE
      - README.md
      - android/src/fdroid/**
      - android/src/google/**
      - iphone/**
      - data/strings/**
      - docs/**
      - generator/**
      - packaging/**
      - pyhelpers/**
      - qt*/**
      - skin_generator/**
      - tools/**
      - track_generator/**
      - xcode/**

jobs:
  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure in Open Source mode
        shell: bash
        run: ./configure.sh

      - name: Lint
        shell: bash
        working-directory: android
        run: gradle lint

  android-check:
    name: Build Android Debug
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [WebDebug, FdroidBeta]

    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 200 # enough to get all commits for the current day

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --depth 1 --init --recursive --jobs=$(($(nproc) * 20))

      - name: Configure in Open Source mode
        shell: bash
        run: ./configure.sh

      - name: Compile ${{ matrix.flavor }}
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          gradle -Parm64 assemble${{ matrix.flavor }}

      - name: Upload arm64-v8a ${{ matrix.flavor }} apk
        uses: actions/upload-artifact@v3
        with:
          name: android-arm64-v8a-${{ matrix.flavor }}
          path: android/build/outputs/apk/**/OrganicMaps-*.apk
          if-no-files-found: error
