name: Android Beta
on:
  workflow_dispatch:

jobs:
  android-web-beta:
    name: Android Web Beta
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: Install build tools and dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=$(($(nproc) * 2))

      - name: Checkout private keys
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.PRIVATE_REPO }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
          ref: master
          path: private.git

      - name: Configure repo with private keys
        shell: bash
        run: |
          ./configure.sh ./private.git
          rm -rf ./private.git

      - name: Set up SDK
        shell: bash
        run: (cd tools/android; ./set_up_android.py --sdk $ANDROID_SDK_ROOT)

      - name: Compile
        shell: bash
        working-directory: android
        run: |
          cmake --version
          ninja --version
          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta

      - name: Upload beta apk to App Distribution
        shell: bash
        working-directory: android
        run: |
           git --no-pager show -s --format='%s%n%n%b' HEAD > RELEASE
           ./gradlew appDistributionUploadWebBeta
