name: iOS Check
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - .github/workflows/ios-check-metadata.yaml  # Run check on self change
      - iphone/metadata/**
      - tools/python/check_store_metadata.py

jobs:
  ios-check-metadata:
    name: Check app metadata
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check metadata
        run: ./tools/python/check_store_metadata.py ios
