name: iOS Check
on:
  workflow_dispatch: # Manual trigger
  pull_request:
    paths-ignore:
      - .gitignore
      - .github/**
      - '**/*_tests/**'
      - '**/CMakeLists.txt'
      - CONTRIBUTORS
      - LICENSE
      - NOTICE
      - README.md
      - android/**
      - docs/**
      - generator/**
      - packaging/**
      - pyhelpers/**
      - qt*/**
      - skin_generator/**
      - tools/**
      - track_generator/**

jobs:
  ios-check:
    name: Build iOS Debug
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: [Debug, Release]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Parallel submodules checkout
        shell: bash
        run: git submodule update --init --recursive --jobs=4

      - name: Configure
        shell: bash
        run: ./configure.sh

      - name: Compile
        shell: bash
        # Check for compilation errors.
        run: |
          xcodebuild \
            -workspace xcode/omim.xcworkspace \
            -scheme OMaps \
            -configuration ${{ matrix.buildType }} build \
            'generic/platform=iOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

  ios-check-metadata:
    name: Check app metadata
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check metadata
        run: ./tools/python/check_store_metadata.py ios
