name: Timezone check

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/timezone-check.yaml'
      - 'data/generator/timezone/timezone_info.json'
      - 'tools/python/timezone'

jobs:
  timezone-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run timezone validator
        run: tools/python/timezone/timezone_info_validator.py
